  
name: Github CI
on: 
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: "!(contains(github.event.head_commit.message, 'skip ci') || contains(github.event.pull_request.title, 'wip') || github.event.pull_request.draft)"
    name: Create demo release build
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
  
    - name: Dotnet restore
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      run: dotnet restore
  
    - name: Release Build
      if: ${{ success() }}
      run: dotnet build --no-restore --configuration Release
